app:
  jwt:
    secret: ${JWT_SECRET:segredo-de-teste-com-mais-de-32-bytes-para-hs256}

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
